[package]
name = "dropin-target-dart"
version = "0.6.7-0"
description = "drop'in Dart code generation"
license.workspace = true
homepage.workspace = true
authors.workspace = true
edition.workspace = true
