[book]
authors = ["Nazim Lachter","Vulcain"]
language = "en"
multilingual = false
src = "src"
title = "drop'in recipes"

[output.html]
git-repository-url = "https://github.com/blue-forest/dropin"
edit-url-template = "https://github.com/blue-forest/dropin/edit/main/docs/{path}"

[output.html.print]
enable = false
