site_name: drop'in
site_url: https://dropin.recipes/
site_author: Blue Forest

nav:
- index.md
- roadmap.md
- dropin.cloud:
  - cloud/index.md
  - cloud/studio.md
  - cloud/editor.md
  - cloud/catalog.md
  - cloud/community.md
- Concepts:
  - concepts/index.md
  - Recipes:
    - concepts/recipes/index.md
    - concepts/recipes/formats.md
    - concepts/recipes/options.md
    - concepts/recipes/getters.md
    - concepts/recipes/setters.md
  - Catalog:
    - concepts/catalog/index.md
    - concepts/catalog/models.md
    - concepts/catalog/projects.md
  - Owners:
    - concepts/owners/index.md
    - concepts/owners/users.md
    - concepts/owners/organizations.md
  - Interfaces:
    - concepts/interfaces/index.md
    - concepts/interfaces/themes.md
    - concepts/interfaces/components.md
    - concepts/interfaces/styles.md
    - concepts/interfaces/pages.md
    - concepts/interfaces/sessions.md
  - Storage:
    - concepts/storage/index.md
    - concepts/storage/collections.md
    - concepts/storage/volumes.md
    - concepts/storage/metrics.md
    - concepts/storage/logs.md
    - concepts/storage/values.md
    - concepts/storage/repositories.md
    - concepts/storage/containers.md
  - Automations:
    - concepts/automations/index.md
    - concepts/automations/functions.md
    - concepts/automations/triggers.md
    - concepts/automations/migrations.md
    - concepts/automations/deployments.md
  - Validations:
    - concepts/validations/index.md
    - concepts/validations/types.md
    - concepts/validations/issues.md
    - concepts/validations/syntaxes.md
  - Auth:
    - concepts/auth/index.md
    - concepts/auth/realms.md
    - concepts/auth/tokens.md
    - concepts/auth/permissions.md
    - concepts/auth/groups.md
  - Endpoints:
    - concepts/endpoints/index.md
    - concepts/endpoints/domains.md
    - concepts/endpoints/connectors.md
    - concepts/endpoints/addresses.md
    - concepts/endpoints/providers.md
    - concepts/endpoints/databases.md
  - Editor:
    - concepts/editor/index.md
    - concepts/editor/sections.md
    - concepts/editor/visualizations.md
    - concepts/editor/forms.md
    - concepts/editor/maps.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
  - navigation.indexes
  - navigation.sections
  - navigation.tracking
  - navigation.prune
  - navigation.top
  - toc.follow

plugins:
- search: { lang: [ en, fr ] }
- tags
- i18n:
    languages:
      en: { name: English }
      fr: { name: Français }
    default_language: en
    nav_translations:
      fr:
        Recipes: Recettes
        Catalog: Catalogue
        Owners: Propriétaires
        Storage: Stockage
        Automations: Automatisations
        Endpoints: Points de terminaison
        Auth: Authentification
        Editor: Éditeur

markdown_extensions:
- attr_list
- def_list

extra_css: [ assets/style.css ]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/blue-forest/dropin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/blueforest_cc
