site_name: drop'in Recipes
site_url: https://dropin.recipes/
site_author: Blue Forest

nav:
- index.md
- index.fr.md
- roadmap.md
- roadmap.fr.md
- concepts:
  - concepts/index.md
  - auth:
    - concepts/auth/index.md
    - concepts/auth/tokens.md
    - concepts/auth/tokens.fr.md

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
  - navigation.instant
  - navigation.expand
  - navigation.indexes
  - toc.follow

extra_css: [ extra.css ]

plugins:
- search: { lang: [ en, fr ] }
- i18n:
    languages:
      en: English
      fr: Français
    default_language: en
    no_translation:
      en: This page is not available in English.
      fr: Cette page n'est pas disponible en français.

extra:
  alternate:
  - { name: English, link: "", lang: en }
  - { name: Français, link: index.fr/, lang: fr }
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/blue-forest
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/blueforest_cc
