site_name: drop'in Recipes
site_url: https://dropin.recipes/
site_author: Blue Forest

nav:
- index.md
- roadmap.md
- Concepts:
  - concepts/index.md
  - Auth:
    - concepts/auth/index.md
    - concepts/auth/tokens.md

theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: logo.png
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
  #- navigation.instant
  - navigation.expand
  - navigation.indexes
  - toc.follow

extra_css: [ style.css ]

plugins:
- search: { lang: [ en, fr ] }
- i18n:
    languages:
      en: { name: English }
      fr: { name: Français }
    default_language: en
    nav_translations:
      fr:
        Auth: Authentification (Auth)

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/blue-forest
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/blueforest_cc
