site_name: drop'in Recipes
site_url: https://dropin.recipes/
site_author: Blue Forest

nav:
- index.md
- roadmap.md
- Concepts:
  - concepts/index.md
  - Catalog:
    - concepts/catalog/index.md
    - concepts/catalog/models.md
    - concepts/catalog/projects.md
  - Automations:
    - concepts/automations/index.md
    - concepts/automations/functions.md
    - concepts/automations/triggers.md
    - concepts/automations/migrations.md
    - concepts/automations/deployments.md
  - Auth:
    - concepts/auth/index.md
    - concepts/auth/realms.md
    - concepts/auth/permissions.md
    - concepts/auth/tokens.md

theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: logo.png
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
  - navigation.expand
  - navigation.indexes
  - toc.follow

plugins:
- search: { lang: [ en, fr ] }
- tags
- i18n:
    languages:
      en: { name: English }
      fr: { name: Français }
    default_language: en
    nav_translations:
      fr:
        Auth: Authentification

markdown_extensions:
- attr_list

extra_css: [ style.css ]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/blue-forest
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/blueforest_cc
