site_name: drop'in Recipes
site_url: https://dropin.recipes/
site_author: Blue Forest

nav:
- index.md
- roadmap.md
- Concepts:
  - concepts/index.md
  - Recipes:
    - concepts/recipes/index.md
  - Catalog:
    - concepts/catalog/index.md
    - concepts/catalog/models.md
    - concepts/catalog/projects.md
  - Owners:
    - concepts/owners/index.md
  - Interfaces:
    - concepts/interfaces/index.md
  - Storage:
    - concepts/storage/index.md
  - Automations:
    - concepts/automations/index.md
    - concepts/automations/functions.md
    - concepts/automations/triggers.md
    - concepts/automations/migrations.md
    - concepts/automations/deployments.md
  - Validations:
    - concepts/validations/index.md
  - Endpoints:
    - concepts/endpoints/index.md
  - Auth:
    - concepts/auth/index.md
    - concepts/auth/realms.md
    - concepts/auth/permissions.md
    - concepts/auth/tokens.md
  - Editor:
    - concepts/editor/index.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
  - navigation.indexes
  - toc.follow

plugins:
- search: { lang: [ en, fr ] }
- tags
- i18n:
    languages:
      en: { name: English }
      fr: { name: Français }
    default_language: en
    nav_translations:
      fr:
        Recipes: Recettes
        Catalog: Catalogue
        Owners: Propriétaires
        Storage: Stockage
        Automations: Automatisations
        Endpoints: Points de terminaison
        Auth: Authentification
        Editor: Éditeur

markdown_extensions: [ attr_list ]

extra_css: [ assets/style.css ]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/blue-forest
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/blueforest_cc
