[workspace]
members = [
  "crates/bootstrap",
  "crates/debugger",
  "crates/modules",
  "crates/utils",
]
exclude = ["etc/sandbox"]

[package]
name = "dropin"
version = "0.5.3-3"
authors = ["Nazim Lachter <nazim@blueforest.cc>", "Vulcain <vulcain@blueforest.cc>"]
edition = "2021"
description = "drop'in [WIP]"
repository = "https://github.com/blue-forest/dropin"
license = "AGPL-3.0-only"
keywords = ["WebAssembly"]

[profile.release]
strip = "symbols"

[dependencies]
dropin-utils = { path = "./crates/utils", version = "0.5.3-2" }
dropin-bootstrap = { path = "./crates/bootstrap", version = "0.5.3-2" }
dialoguer = "0.10.0"
edit = "0.1.3"
home = "0.5.3"
path-clean = "0.1.0"
regex = "1.5.5"
serde = "1.0.136"
serde_derive = "1.0.136"
structopt = "0.3"
toml = "0.5.8"
wasmtime = "0.36"
wasmtime-wasi = "0.36"

[[bin]]
name = "dropin"
path = "src/main.rs"
test = false
bench = false

