[package]
name = "dropin"
version = "0.5.3-0"
authors = ["Nazim Lachter <nazim@blueforest.cc>", "Vulcain <vulcain@blueforest.cc>"]
edition = "2021"
description = "drop'in WebAssembly compiler [ALPHA]"
repository = "https://github.com/blue-forest/dropin-compiler"
license = "AGPL-3.0-only"
keywords = ["WebAssembly"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
structopt = "0.3"
termion = "1.5.6"
wasmtime = "0.34.1"
wasmtime-wasi = "0.34.1"
