[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.buildCore]
command = "cargo"
args = [
  "build",
  "-p", "dropin-core",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.buildBootstrap]
command = "cargo"
args = [
  "build",
  "-p", "dropin-bootstrap",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.prePublish]
dependencies = [ "buildCore", "buildBootstrap" ]
script = '''
PACKAGE_ROOT="target/package/${CARGO_MAKE_CRATE_NAME}-${CARGO_MAKE_CRATE_VERSION}"
PACKAGE_WASM_TARGET="${PACKAGE_ROOT}/target/wasm32-unknown-unknown/release"
WASM_TARGET="target/wasm32-unknown-unknown/release"
mkdir -p ${PACKAGE_WASM_TARGET}
cp ${WASM_TARGET}/dropin_core.wasm ${PACKAGE_WASM_TARGET}
cp ${WASM_TARGET}/dropin_bootstrap.wasm ${PACKAGE_WASM_TARGET}
'''

[tasks.publish]
dependencies = [ "prePublish" ]
command = "cargo"
args = [ "publish", "${@}" ]

[tasks.build]
dependencies = [
  "buildCore",
  "buildBootstrap",
]
