[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DROPIN_PM_HOST = "https://pm.dropin.dev.blueforest.cc"

[config]
default_to_workspace = false

[tasks.buildCore]
command = "cargo"
args = [
  "build",
  "-p", "dropin-core",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.buildBootstrap]
command = "cargo"
args = [
  "build",
  "-p", "dropin-bootstrap",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.requirePMToken]
script = '''
[[ -v DROPIN_PM_TOKEN ]] || \
(
  echo "Please provide a token in the environment variable DROPIN_PM_TOKEN" && \
  false \
)
'''

[tasks.publishPMCore]
dependencies = [ "requirePMToken", "buildCore" ]
command = "curl"
args = [
  "-f",
  "-X", "POST",
  "--data-binary", "@target/wasm32-unknown-unknown/release/dropin_core.wasm",
  "${DROPIN_PM_HOST}/blueforest/dropin-core/v1/${DROPIN_PM_TOKEN}",
]

[tasks.publishPMBootstrap]
dependencies = [ "requirePMToken", "buildBootstrap" ]
command = "curl"
args = [
  "-f",
  "-X", "POST",
  "--data-binary", "@target/wasm32-unknown-unknown/release/dropin_bootstrap.wasm",
  "${DROPIN_PM_HOST}/blueforest/dropin-bootstrap/v1/${DROPIN_PM_TOKEN}",
]

[tasks.publishPM]
dependencies = [ "publishPMCore", "publishPMBootstrap" ]

[tasks.publish]
command = "cargo"
args = [ "publish", "${@}" ]

[tasks.build]
args = [ "build", "${@}" ]

[tasks.run]
command = "cargo"
args = [ "run", "${@}" ]
