[package]
name = "dropin-compiler-parser-tools"
version = "0.1.0"
license.workspace = true
homepage.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
dropin-compiler-parser-lib = { path = "../lib" }

anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
