[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.buildCore]
private = true
command = "cargo"
args = [
  "build",
  "-p", "dropin-core",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.buildBootstrap]
private = true
command = "cargo"
args = [
  "build",
  "-p", "dropin-bootstrap",
  "--target", "wasm32-unknown-unknown",
  "--release"
]

[tasks.buildWasm]
dependencies = [ "buildCore", "buildBootstrap" ]
script = '''
TARGET="target/wasm32-unknown-unknown/release"
BUILD="recipes/.builds/blueforest"
cp ${TARGET}/dropin_core.wasm ${BUILD}/dropin-core_v1.wasm
cp ${TARGET}/dropin_bootstrap.wasm ${BUILD}/dropin-bootstrap_v1.wasm
'''

[tasks.requirePMToken]
private = true
script = '''
[[ -v DROPIN_PM_TOKEN ]] || \
(
  echo "Please provide a token in the environment variable DROPIN_PM_TOKEN" && \
  false \
)
'''

[tasks.publishPMCore]
dependencies = [ "requirePMToken", "buildWasm" ]
command = "cargo"
args = [
  "run", "-p", "dropin-pm", "--", "blueforest", "dropin-core", "v1"
]

[tasks.publishPMBootstrap]
dependencies = [ "requirePMToken", "buildWasm" ]
command = "cargo"
args = [
  "run", "-p", "dropin-pm", "--", "blueforest", "dropin-bootstrap", "v1",
]

[tasks.publishPM]
dependencies = [ "publishPMCore", "publishPMBootstrap" ]

[tasks.publish]
command = "cargo"
args = [ "publish", "${@}" ]

[tasks.build]
args = [ "build", "${@}" ]

[tasks.run]
command = "cargo"
args = [ "run", "${@}" ]
