[package]
name = "dropin-target-flutter"
version = "0.6.7-0"
description = "drop'in flutter code generation"
license.workspace = true
homepage.workspace = true
authors.workspace = true
edition.workspace = true

[features]
coverage = []
