;     _              _ _
;  __| |_ _ ___ _ __( |_)_ _
; / _` | '_/ _ \ '_ \/| | ' \
; \__,_|_| \___/ .__/ |_|_||_| dropin-compiler
;              |_|
; Copyright © 2019-2024 Blue Forest
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program. If not, see <https://www.gnu.org/licenses/>.

predicate = expression predicate-continuation-
predicate-continuation- = "&" expression predicate-continuation-
predicate-continuation- =/ "|" expression predicate-continuation-
predicate-continuation- =/ EMPTY

expression = value expression-continuation-
expression =/ "-" value expression-continuation-
expression =/ if
expression-continuation- = "==" value
expression-continuation- =/ "!=" value
expression-continuation- =/ "in" value
expression-continuation- =/ LESSTHAN value
expression-continuation- =/ MORETHAN value
expression-continuation- =/ ATLEAST value
expression-continuation- =/ ATMOST value
expression-continuation- =/ "+" value expression-continuation-
expression-continuation- =/ "-" value expression-continuation-
expression-continuation- =/ EMPTY

value = INDENT value-indent / value-no-indent

value-no-indent = PARSPACED predicate ")" value-continuation-
value-no-indent =/ ID id-continuation-
value-no-indent =/ "?" value
value-no-indent =/ "!" value
value-no-indent =/ value-lit

value-lit = TEXT
value-lit =/ QUANTITY
value-lit =/ TRUE / FALSE
value-lit =/ BRACSPACED "]"
value-lit =/ "{" value-braces-
value-lit =/ "\" INDENT value-indent

value-braces- = object-empty / anonymous-function

id-continuation- = "{" anonymous-function / value-continuation-
value-continuation- = "." ID value-continuation-
value-continuation- =/ BRACGLUED value "]" value-continuation-
value-continuation- =/ function-call value-continuation-
value-continuation- =/ EMPTY

value-indent = ID value-indent-id- / list-lit
value-indent-id- = object / value-continuation- list-id

object = object-value object-next- DEINDENT
object-key = ID object-value object-next-
object-next- = NEWLINE object-key / EMPTY
object-value = value / SAMEKEY
object-empty = "}"

list-id = list-value-next- DEINDENT
list-lit = value-lit list-value-next- DEINDENT
list-value-next- = NEWLINE value-no-indent list-value-next- / EMPTY

function-call = PARGLUED function-call-args- ")"
function-call-args- = value function-call-args-next-
function-call-args- =/ EMPTY
function-call-args-next- = "," function-call-args-
function-call-args-next- =/ EMPTY

anonymous-function = newlines function-args ":" predicate "}" anonymous-function-call-
function-args = ID function-args-next-
function-args-next- = "," ID function-args-next-
function-args-next- =/ EMPTY
anonymous-function-call- = function-call / EMPTY

if = IF predicate ":" if-then if-else
if-then = value-no-indent
if-then =/ INDENT value-no-indent DEINDENT
if-else = ELSE ":" if-then / EMPTY

newlines = NEWLINE newlines
newlines =/ INDENT newlines
newlines =/ DEINDENT newlines
newlines =/ EMPTY
