(module
  (memory (export "memory") 1)
  (table $table (export "table") 1 funcref)
  (data (i32.const 420) "test ok\n")
  (func $elem (result i32 i32)
    (i32.const 420)
    (i32.const 8)
  )
  (elem funcref (item (ref.func $elem)))
  (func $init (export "init")
    (i32.const 0xd2)
    (i32.const 0x00)
    (i32.const 0x0b)
    (table.init 0 0)
  )
)
