name: Compiler tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ compiler/**/* ]

defaults:
  run:
    working-directory: ./compiler

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Run tests
      run: cargo test --verbose
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'

    - name: rust-grcov
      uses: actions-rs/grcov@v0.1

    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
