name: crates.io publish
on:
  push:
    branches: [ main ]
    paths: [ src/**/*, crates/*/src/**/* ]
  workflow_dispatch:
jobs:
  publish:
    environment: crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - run: cargo publish --token ${CRATES_TOKEN} -p dropin-utils
      if: always()
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - run: cargo publish --token ${CRATES_TOKEN} -p dropin-bootstrap
      if: always()
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - run: cargo publish --token ${CRATES_TOKEN}
      if: always()
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
