name: GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ recipes/**/* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      working-directory: ./recipes
    steps:
    - uses: actions/checkout@v2

    - name: MkDocs build
      uses: Tiryoh/actions-mkdocs@v0

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        cname: dropin.recipes
