name: GitHub Pages (MkDocs)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ recipes/**/* ]

defaults:
  run:
    working-directory: ./recipes

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with: { python-version: 3.x }
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build MkDocs
      run: mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./recipes/site
        cname: dropin.recipes
