name: GitHub Pages (mdBook)

on:
  push:
    branches: [ main ]
    paths: [ recipes/**/* ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ false }} # TEMPORARY DISABLED
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build
        working-directory: ./etc/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./etc/docs/book
          cname: dropin.recipes
