name: Rust checks
on:
  push:
    paths: [ src/**/*, crates/*/src/**/* ]
  workflow_dispatch:
jobs:
  rust_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Build core
      run: cargo build --verbose -p dropin-core --target wasm32-unknown-unknown --release
    - name: Build bootstrap
      run: cargo build --verbose -p dropin-bootstrap --target wasm32-unknown-unknown --release
    - name: Build CLI
      run: cargo build --verbose
    - name: Build
      run: cargo build --verbose
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -D warnings
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: cargo test --verbose
